services:
  caddy:
    image: docker.io/caddy
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./.caddy:/data/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/app
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
