services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    restart: unless-stopped
    volumes:
      - ./data/wg-easy/:/etc/wireguard/
    ports:
      # WireGuard VPN port
      - "51820:51820/udp"
      # Admin panel
      - "51821:51821/tcp"
    environment:
      - WG_HOST=${HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_DEFAULT_ADDRESS=192.168.100.x
      - WG_DEFAULT_DNS=9.9.9.9
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
