services:
  xray:
    image: ghcr.io/xtls/xray-core
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/xray/config.json
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
