services:
  xray:
    image: ghcr.io/xtls/xray-core
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/xray/config.json
    ports:
      - "443:443/tcp"
    cap_add:
      - NET_BIND_SERVICE
    command: ["run", "-c", "/etc/xray/config.json"]
